# .pre-commit-config.yaml
# See https://pre-commit.com for more information
# Example pre-commit configuration:
# repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0 # Use the latest version
#     hooks:
#     -   id: trailing-whitespace
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     -   id: check-added-large-files
# -   repo: https://github.com/psf/black
#     rev: 24.4.2 # Use the version compatible with your project
#     hooks:
#     -   id: black
# -   repo: https://github.com/pycqa/flake8
#     rev: '7.0.0' # Use the version compatible with your project
#     hooks:
#     -   id: flake8
